# This is a basic workflow to help you get started with Actions

name: CI_pull_req

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
        
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.results }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Automation start
        id: step1
        uses: ./
        with:
          #github_token: ${{secrets.GITHUB_TOKEN}}
          iap_token: ${{secrets.IAP_TOKEN}}
          iap_instance: ${{secrets.IAP_INSTANCE}}
          #time_interval: 1
          no_of_attempts: 200
          api_endpoint: ${{secrets.API_ENDPOINT}}
          api_endpoint_body: ${{secrets.API_ENDPOINT_BODY}}
          automation_status: 1
      - name: Get output
        run: echo "${{steps.step1.outputs.results}}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{needs.job1.outputs.output1}}"
